AWSTemplateFormatVersion: '2010-09-09'
Resources:
  AWSIAMRoleDevelopment0001:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement: 
          - Effect: "Allow"
            Principal: 
              Service: 
                - "ec2.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      Path: "/"
      ManagedPolicyArns:
        - 文字列
      Policies:
        - Policies
      RoleName: String

Outputs:
  AWSIAMRoleDevelopment0001:
    Value: !Ref AWSIAMRoleDevelopment0001
    Export:
      Name: AWSIAMRoleDevelopment0001