AWSTemplateFormatVersion: '2010-09-09'
Resources:
  RDSDBInstanceDevelopment0001:
    Type: AWS::RDS::DBInstance
    Properties: 
      AllocatedStorage: 100
      # CharacterSetName: ''
      # DBSnapshotIdentifier: ''
      DBName: 'RDSDBInstanceDevelopment0001'
      DBInstanceIdentifier: 'rds-dbinstance-development-0001'
      DBParameterGroupName: !Ref RDSDBParameterGroupDevelopment0001
      DBSubnetGroupName: !Ref RDSDBSubnetGroupDevelopment0001
      DBInstanceClass: 'db.t2.small'
      Engine: postgres
      EngineVersion: '9.6.6'
      MultiAZ: 'true'
      Port: 5432
      MasterUsername: 'postgres'
      MasterUserPassword: 'Shibuya1-Choume'
      Tags: 
        - Key: Name
          Value: RDS::DBInstance::Development0001

  RDSDBSubnetGroupDevelopment0001:
    Type: AWS::RDS::DBSubnetGroup
    Properties: 
      DBSubnetGroupDescription: 'postgres'
      # DBSubnetGroupName: String
      SubnetIds:
        - !ImportValue EC2SubnetDevelopment0003
        - !ImportValue EC2SubnetDevelopment0004
      Tags:
        - Key: Name
          Value: RDS::DBSubnetGroup::Development0001

  RDSDBParameterGroupDevelopment0001:
    Type: AWS::RDS::DBParameterGroup
    Properties: 
      Description: 'postgres'
      Family: 'postgres9.6'
      Parameters:
        timezone: 'Asia/Tokyo'
      Tags:
        - Key: Name
          Value: RDS::DBParameterGroup::Development0001

# Outputs:
#   RDSDBInstanceDevelopment0001:
#     Value: !Ref RDSDBInstanceDevelopment0001
#     Export:
#       Name: RDSDBInstanceDevelopment0001