AWSTemplateFormatVersion: '2010-09-09'
Resources:
  RDSDBInstanceDevelopment0001:
    Type: AWS::RDS::DBInstance
    Properties: 
      AllocatedStorage: 100
      # CharacterSetName: ''
      # DBSnapshotIdentifier: ''
      DBName: 'development'
      DBInstanceIdentifier: 'rds-dbinstance-development-0001'
      DBParameterGroupName: !Ref RDSDBParameterGroupDevelopment0001
      DBSubnetGroupName: !Ref RDSDBSubnetGroupDevelopment0001
      DBInstanceClass: 'db.t2.small'
      Engine: mysql
      EngineVersion: '5.6.39'
      MultiAZ: 'false'
      Port: 3306
      MasterUsername: 'byson'
      MasterUserPassword: 'Shibuya1-Choume'
      VPCSecurityGroups: 
        - !ImportValue EC2SecurityGroupDevelopmentMySQLFromPublic0007
      Tags: 
        - Key: Name
          Value: RDS::DBInstance::Development0001

  RDSDBSubnetGroupDevelopment0001:
    Type: AWS::RDS::DBSubnetGroup
    Properties: 
      DBSubnetGroupDescription: 'mysql'
      # DBSubnetGroupName: String
      SubnetIds:
        - !ImportValue EC2SubnetDevelopment0003
        - !ImportValue EC2SubnetDevelopment0004
      Tags:
        - Key: Name
          Value: Development0001

  RDSDBParameterGroupDevelopment0001:
    Type: AWS::RDS::DBParameterGroup
    Properties: 
      Description: 'MySQL'
      Family: 'MySQL5.6'
      # Parameters:
        # timezone: 'Asia/Tokyo'
      Tags:
        - Key: Name
          Value: Development0001

# Outputs:
#   RDSDBInstanceDevelopment0001:
#     Value: !Ref RDSDBInstanceDevelopment0001
#     Export:
#       Name: RDSDBInstanceDevelopment0001